version: "3.8"
services:
  db:
    image: postgres:15
    container_name: badminton_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: badminton_reservation
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
